# -*- coding: utf-8 -*-

#########################################################################
## This scaffolding model makes your app work on Google App Engine too
## File is released under public domain and you can use without limitations
#########################################################################

## if SSL/HTTPS is properly configured and you want all HTTP requests to
## be redirected to HTTPS, uncomment the line below:
# request.requires_https()
import json
import datetime

import logging
logger = logging.getLogger('web2py.app.studybuddies')
logger.setLevel(logging.DEBUG)
from conf import *

from gluon.custom_import import track_changes
track_changes(True)

if not request.env.web2py_runtime_gae:
	## if NOT running on Google App Engine use SQLite or other DB
	db = DAL(DB_URI)
	session.connect(request, response, db=db, masterapp='javelin')
else:
	## connect to Google BigTable (optional 'google:datastore://namespace')
	db = DAL('google:datastore')
	## store sessions and tickets there
	session.connect(request, response, db=db)
	## or store session in Memcache, Redis, etc.
	## from gluon.contrib.memdb import MEMDB
	## from google.appengine.api.memcache import Client
	## session.connect(request, response, db = MEMDB(Client()))

from globals import current
from gluon.storage import Storage
current.javelin = Storage()
current.javelin.db = db

## by default give a view/generic.extension to all actions from localhost
## none otherwise. a pattern can be 'controller/function.extension'
response.generic_patterns = ['*'] if request.is_local else []
## (optional) optimize handling of static files
# response.optimize_css = 'concat,minify,inline'
# response.optimize_js = 'concat,minify,inline'

#########################################################################
## Here is sample code if you need for
## - email capabilities
## - authentication (registration, login, logout, ... )
## - authorization (role based authorization)
## - services (xml, csv, json, xmlrpc, jsonrpc, amf, rss)
## - old style crud actions
## (more options discussed in gluon/tools.py)
#########################################################################

from gluon.tools import Auth, Crud, Service, PluginManager, prettydate
auth = Auth(db)
crud, service, plugins = Crud(db), Service(), PluginManager()

## add field for user.active
auth.settings.extra_fields['auth_user'] = [Field('active', 'boolean', default=True)]

## create all tables needed by auth if not custom tables
auth.define_tables(username=True, signature=False, migrate=False)

## configure email
mail = auth.settings.mailer
mail.settings.server = 'smtp.gmail.com:587'
mail.settings.sender = 'vc2messager@gmail.com'
mail.settings.login = 'vc2messager:akwpyddynlbfrhzt'

current.javelin.mail = mail

# Replace user, password, server and port in the connection string
# Set port as 993 for SSL support
# imapdb = DAL("imap://vc2messager:srivijaya@imap.gmail.com:993", pool_size=1)
# imapdb.define_tables()

## configure auth policy
auth.settings.registration_requires_verification = True
auth.settings.registration_requires_approval = True
auth.settings.reset_password_requires_verification = True
auth.settings.register_fields=['first_name', 'last_name', 'email', 'username', 'password']
auth.settings.profile_fields=['first_name', 'last_name', 'email', 'username']
auth.settings.hmac_key = "sha512:93b42428-33e2-4c1d-bfa0-2de193983bd8"

## if you need to use OpenID, Facebook, MySpace, Twitter, Linkedin, etc.
## register with janrain.com, write your domain:api_key in private/janrain.key
from gluon.contrib.login_methods.rpx_account import use_janrain
use_janrain(auth, filename='private/janrain.key')

#########################################################################
## Define your tables below (or better in another model file) for example
##
## >>> db.define_table('mytable',Field('myfield','string'))
##
## Fields can be 'string','text','password','integer','double','boolean'
##       'date','time','datetime','blob','upload', 'reference TABLENAME'
## There is an implicit 'id integer autoincrement' field
## Consult manual for more options, validators, etc.
##
## More API examples for controllers:
##
## >>> db.mytable.insert(myfield='value')
## >>> rows=db(db.mytable.myfield=='value').select(db.mytable.ALL)
## >>> for row in rows: print row.id, row.myfield
#########################################################################

db.define_table('person',
	Field('student_id', 'integer', notnull=True, unique=True),
	Field('last_name', 'string', notnull=True, required=True),
	Field('first_name', 'string', notnull=True, required=True),
	Field('home_phone', 'string'),
	Field('cell_phone', 'string'),
	Field('cell_provider', 'string'),
	Field('gender', 'string'),
	Field('email', 'string'),
	Field('street', 'string'),
	Field('city', 'string'),
	Field('state', 'string'),
	Field('zip_code', 'string'),
	Field('notes', 'string'),
	Field('pic', 'blob'),
	Field('crew', 'integer', default=None, ondelete='SET NULL'),
	Field('grade', 'integer'),
	Field('leader', 'boolean', default=False), migrate=False)

db.define_table('dept',
	Field('title', 'string', notnull=True), migrate=False)

db.define_table('sb_section',
	Field('title', 'string'),
	Field('dept_id', 'reference dept'))

db.define_table('sb_att',
	Field('person_id', 'reference person'),
	Field('sb_section_id', 'reference sb_section'),
	Field('in_time', 'datetime', default=request.now),
	Field('out_time', 'datetime', default=None, update=request.now),
	Field('studyhour', 'integer', default=0),
	Field('is_out', 'boolean', default=False))

def days_equal(dateone, datetwo):
	return dateone.date() == datetwo.date()

# db.sb_att.event_date.__eq__ = days_equal

from gluon.storage import Storage

# people = [
# Storage(student_id=1, last_name="Soto", first_name="Georgetta", grade=11),
# Storage(student_id=2, last_name="Bradford", first_name="Nguyet", grade=12),
# Storage(student_id=3, last_name="Burks", first_name="Charissa", grade=9),
# Storage(student_id=4, last_name="Norton", first_name="Latarsha", grade=9),
# Storage(student_id=5, last_name="Mathews", first_name="Chas", grade=9),
# Storage(student_id=6, last_name="Shaw", first_name="Athena", grade=10),
# Storage(student_id=7, last_name="Mcbride", first_name="Suzan", grade=10),
# Storage(student_id=8, last_name="Garrison", first_name="Phoebe", grade=9),
# Storage(student_id=9, last_name="Wilkerson", first_name="Amberly", grade=11),
# Storage(student_id=10, last_name="Henson", first_name="Broderick", grade=11),
# Storage(student_id=11, last_name="Blake", first_name="Barry", grade=9),
# Storage(student_id=12, last_name="Kidd", first_name="Angelique", grade=11),
# Storage(student_id=13, last_name="Carter", first_name="Bok", grade=10),
# Storage(student_id=14, last_name="Huffman", first_name="Rebekah", grade=10),
# Storage(student_id=15, last_name="Crosby", first_name="Jacquelin", grade=12),
# Storage(student_id=16, last_name="Miller", first_name="Nicol", grade=9),
# Storage(student_id=17, last_name="Sampson", first_name="Jame", grade=11),
# Storage(student_id=18, last_name="Lawson", first_name="Reynalda", grade=10),
# Storage(student_id=19, last_name="Nielsen", first_name="Georgia", grade=9),
# Storage(student_id=20, last_name="Carter", first_name="Georgina", grade=9),
# Storage(student_id=21, last_name="Collier", first_name="Demetrice", grade=9),
# Storage(student_id=22, last_name="Baxter", first_name="Zulma", grade=12),
# Storage(student_id=23, last_name="Ayers", first_name="Siobhan", grade=9),
# Storage(student_id=24, last_name="Nelson", first_name="Pasquale", grade=10),
# Storage(student_id=25, last_name="Rodriquez", first_name="Bell", grade=9),
# Storage(student_id=26, last_name="Lyons", first_name="Delmy", grade=9),
# Storage(student_id=27, last_name="Thornton", first_name="Nathan", grade=10),
# Storage(student_id=28, last_name="Curtis", first_name="Denyse", grade=11),
# Storage(student_id=29, last_name="Simmons", first_name="Phillip", grade=12),
# Storage(student_id=30, last_name="Richard", first_name="Reanna", grade=11),
# Storage(student_id=31, last_name="Jimenez", first_name="Eloise", grade=9),
# Storage(student_id=32, last_name="Daniels", first_name="Narcisa", grade=10),
# Storage(student_id=33, last_name="Shannon", first_name="Tamica", grade=9),
# Storage(student_id=34, last_name="Briggs", first_name="Yu", grade=11),
# Storage(student_id=35, last_name="Howe", first_name="Sylvia", grade=12),
# Storage(student_id=36, last_name="Oneill", first_name="Lanora", grade=11),
# Storage(student_id=37, last_name="Chapman", first_name="Flavia", grade=12),
# Storage(student_id=38, last_name="Mclaughlin", first_name="Edwardo", grade=10),
# Storage(student_id=39, last_name="Brock", first_name="Avril", grade=10),
# Storage(student_id=40, last_name="Merritt", first_name="Scott", grade=12),
# Storage(student_id=41, last_name="Estrada", first_name="Hobert", grade=12),
# Storage(student_id=42, last_name="Aguilar", first_name="Danyel", grade=9),
# Storage(student_id=43, last_name="Williams", first_name="Jed", grade=10),
# Storage(student_id=44, last_name="House", first_name="Arnoldo", grade=11),
# Storage(student_id=45, last_name="Howell", first_name="Luciano", grade=12),
# Storage(student_id=46, last_name="Lynch", first_name="Lucia", grade=11),
# Storage(student_id=47, last_name="Larsen", first_name="Etha", grade=11),
# Storage(student_id=48, last_name="Chan", first_name="Bradford", grade=10),
# Storage(student_id=49, last_name="Sloan", first_name="Lin", grade=9),
# Storage(student_id=50, last_name="Sanders", first_name="Dionna", grade=10),
# Storage(student_id=51, last_name="Harris", first_name="Natacha", grade=10),
# Storage(student_id=52, last_name="Aguilar", first_name="Vivian", grade=12),
# Storage(student_id=53, last_name="Holland", first_name="Roderick", grade=9),
# Storage(student_id=54, last_name="Mcfadden", first_name="Ariane", grade=9),
# Storage(student_id=55, last_name="Vaughn", first_name="Tracee", grade=10),
# Storage(student_id=56, last_name="Dodson", first_name="Macie", grade=9),
# Storage(student_id=57, last_name="Sweet", first_name="Abigail", grade=11),
# Storage(student_id=58, last_name="Banks", first_name="Genaro", grade=11),
# Storage(student_id=59, last_name="Dorsey", first_name="Len", grade=9),
# Storage(student_id=60, last_name="Nixon", first_name="Shin", grade=10),
# Storage(student_id=61, last_name="Baldwin", first_name="Sheila", grade=10),
# Storage(student_id=62, last_name="Joyce", first_name="Gwen", grade=10),
# Storage(student_id=63, last_name="Stevenson", first_name="Cordie", grade=10),
# Storage(student_id=64, last_name="Finley", first_name="Shane", grade=12),
# Storage(student_id=65, last_name="Fry", first_name="Danille", grade=12),
# Storage(student_id=66, last_name="Peck", first_name="Marvin", grade=12),
# Storage(student_id=67, last_name="Woodward", first_name="Lyndia", grade=10),
# Storage(student_id=68, last_name="Ochoa", first_name="Ilene", grade=11),
# Storage(student_id=69, last_name="Dillard", first_name="Anitra", grade=11),
# Storage(student_id=70, last_name="Espinoza", first_name="Arletha", grade=11),
# Storage(student_id=71, last_name="Zimmerman", first_name="Tracie", grade=12),
# Storage(student_id=72, last_name="Blair", first_name="Virgil", grade=11),
# Storage(student_id=73, last_name="Everett", first_name="Wendy", grade=10),
# Storage(student_id=74, last_name="Townsend", first_name="Mitzie", grade=10),
# Storage(student_id=75, last_name="Macias", first_name="Roosevelt", grade=11),
# Storage(student_id=76, last_name="Matthews", first_name="Mack", grade=11),
# Storage(student_id=77, last_name="Collins", first_name="Marline", grade=10),
# Storage(student_id=78, last_name="Stout", first_name="Elroy", grade=9),
# Storage(student_id=79, last_name="Norman", first_name="Marvella", grade=9),
# Storage(student_id=80, last_name="Doyle", first_name="Rosie", grade=9),
# Storage(student_id=81, last_name="Colon", first_name="Merle", grade=10),
# Storage(student_id=82, last_name="Maddox", first_name="Janina", grade=9),
# Storage(student_id=83, last_name="Martin", first_name="Lean", grade=11),
# Storage(student_id=84, last_name="Long", first_name="Kassandra", grade=12),
# Storage(student_id=85, last_name="Copeland", first_name="Asuncion", grade=12),
# Storage(student_id=86, last_name="Rojas", first_name="Melanie", grade=11),
# Storage(student_id=87, last_name="Lara", first_name="Johnetta", grade=9),
# Storage(student_id=88, last_name="Wilson", first_name="Jadwiga", grade=12),
# Storage(student_id=89, last_name="Hanson", first_name="Vikki", grade=12),
# Storage(student_id=90, last_name="Atkinson", first_name="Dylan", grade=12),
# Storage(student_id=91, last_name="Levine", first_name="Nancey", grade=11),
# Storage(student_id=92, last_name="Murray", first_name="Reinaldo", grade=9),
# Storage(student_id=93, last_name="Francis", first_name="Clarita", grade=9),
# Storage(student_id=94, last_name="Duffy", first_name="Esmeralda", grade=12),
# Storage(student_id=95, last_name="Rich", first_name="Glenn", grade=9),
# Storage(student_id=96, last_name="Delgado", first_name="Malia", grade=12),
# Storage(student_id=97, last_name="Wade", first_name="Colene", grade=10),
# Storage(student_id=98, last_name="Branch", first_name="Melva", grade=11),
# Storage(student_id=99, last_name="Mcintosh", first_name="Lieselotte", grade=10),
# Storage(student_id=100, last_name="Hudson", first_name="Johnsie", grade=10),
# Storage(student_id=101, last_name="Owens", first_name="Cristopher", grade=12),
# Storage(student_id=102, last_name="Petersen", first_name="Michel", grade=9),
# Storage(student_id=103, last_name="Calhoun", first_name="Lena", grade=12),
# Storage(student_id=104, last_name="Dillard", first_name="Macie", grade=9),
# Storage(student_id=105, last_name="Bean", first_name="Latrina", grade=11),
# Storage(student_id=106, last_name="Baird", first_name="Coralie", grade=12),
# Storage(student_id=107, last_name="Reilly", first_name="Lyda", grade=10),
# Storage(student_id=108, last_name="Salinas", first_name="Zaida", grade=9),
# Storage(student_id=109, last_name="Cohen", first_name="Bert", grade=12),
# Storage(student_id=110, last_name="Chambers", first_name="Bernarda", grade=11),
# Storage(student_id=111, last_name="Gallegos", first_name="Twanda", grade=9),
# Storage(student_id=112, last_name="Cortez", first_name="Mamie", grade=11),
# Storage(student_id=113, last_name="Morgan", first_name="Korey", grade=11),
# Storage(student_id=114, last_name="Tucker", first_name="Mirian", grade=9),
# Storage(student_id=115, last_name="Tate", first_name="Darlena", grade=12),
# Storage(student_id=116, last_name="Porter", first_name="Kristi", grade=11),
# Storage(student_id=117, last_name="Conrad", first_name="Joni", grade=12),
# Storage(student_id=118, last_name="Byers", first_name="Valene", grade=10),
# Storage(student_id=119, last_name="Ortiz", first_name="Yukiko", grade=12),
# Storage(student_id=120, last_name="Barber", first_name="April", grade=12),
# Storage(student_id=121, last_name="Garcia", first_name="Dario", grade=10),
# Storage(student_id=122, last_name="Neal", first_name="Ellan", grade=12),
# Storage(student_id=123, last_name="Rasmussen", first_name="Alvina", grade=11),
# Storage(student_id=124, last_name="Rich", first_name="Nidia", grade=9),
# Storage(student_id=125, last_name="Guy", first_name="Sherrie", grade=11),
# Storage(student_id=126, last_name="Hammond", first_name="Louvenia", grade=12),
# Storage(student_id=127, last_name="Gentry", first_name="Alisia", grade=10),
# Storage(student_id=128, last_name="Lucas", first_name="Jamey", grade=9),
# Storage(student_id=129, last_name="Fields", first_name="Sonja", grade=10),
# Storage(student_id=130, last_name="Tyler", first_name="Eveline", grade=12),
# Storage(student_id=131, last_name="Johnson", first_name="Leland", grade=10),
# Storage(student_id=132, last_name="Burke", first_name="Ellena", grade=11),
# Storage(student_id=133, last_name="Riley", first_name="Karol", grade=11),
# Storage(student_id=134, last_name="Jordan", first_name="Liana", grade=12),
# Storage(student_id=135, last_name="Strickland", first_name="Jerrell", grade=9),
# Storage(student_id=136, last_name="Peters", first_name="Lakiesha", grade=10),
# Storage(student_id=137, last_name="Clements", first_name="Tracy", grade=12),
# Storage(student_id=138, last_name="Morrow", first_name="Bobbie", grade=11),
# Storage(student_id=139, last_name="Barnett", first_name="Mohamed", grade=11),
# Storage(student_id=140, last_name="Mitchell", first_name="Pamula", grade=12),
# Storage(student_id=141, last_name="Hahn", first_name="Celine", grade=10),
# Storage(student_id=142, last_name="Hickman", first_name="Joi", grade=10),
# Storage(student_id=143, last_name="Lucas", first_name="Hee", grade=11),
# Storage(student_id=144, last_name="Johnson", first_name="Claud", grade=9),
# Storage(student_id=145, last_name="Walter", first_name="Jenny", grade=10),
# Storage(student_id=146, last_name="Brewer", first_name="Hortense", grade=11),
# Storage(student_id=147, last_name="Blair", first_name="Patti", grade=9),
# Storage(student_id=148, last_name="Rosales", first_name="Sara", grade=9),
# Storage(student_id=149, last_name="Mathis", first_name="Rivka", grade=12),
# Storage(student_id=150, last_name="Atkinson", first_name="Velma", grade=9),
# Storage(student_id=151, last_name="Lynn", first_name="Freda", grade=10),
# Storage(student_id=152, last_name="Price", first_name="Bethel", grade=11),
# Storage(student_id=153, last_name="Robbins", first_name="Staci", grade=9),
# Storage(student_id=154, last_name="Rush", first_name="Kurtis", grade=12),
# Storage(student_id=155, last_name="Padilla", first_name="Jose", grade=11),
# Storage(student_id=156, last_name="Gould", first_name="Sophia", grade=10),
# Storage(student_id=157, last_name="Navarro", first_name="Elke", grade=10),
# Storage(student_id=158, last_name="Conley", first_name="Verla", grade=11),
# Storage(student_id=159, last_name="Weber", first_name="Cari", grade=10),
# Storage(student_id=160, last_name="Lancaster", first_name="Letitia", grade=9),
# Storage(student_id=161, last_name="Wade", first_name="Jan", grade=9),
# Storage(student_id=162, last_name="Kline", first_name="Elliott", grade=12),
# Storage(student_id=163, last_name="Haley", first_name="Luba", grade=9),
# Storage(student_id=164, last_name="Shaw", first_name="Andree", grade=12),
# Storage(student_id=165, last_name="Stout", first_name="Annis", grade=9),
# Storage(student_id=166, last_name="Levy", first_name="Marquita", grade=10),
# Storage(student_id=167, last_name="Willis", first_name="Norene", grade=12),
# Storage(student_id=168, last_name="Fulton", first_name="Griselda", grade=12),
# Storage(student_id=169, last_name="Reynolds", first_name="Dawn", grade=12),
# Storage(student_id=170, last_name="Dillard", first_name="Tamala", grade=11),
# Storage(student_id=171, last_name="Benson", first_name="Zaida", grade=9),
# Storage(student_id=172, last_name="Hale", first_name="Michael", grade=10),
# Storage(student_id=173, last_name="Dawson", first_name="Serina", grade=11),
# Storage(student_id=174, last_name="Matthews", first_name="Leigha", grade=9),
# Storage(student_id=175, last_name="Church", first_name="Freddie", grade=9),
# Storage(student_id=176, last_name="Simpson", first_name="Pearlie", grade=9),
# Storage(student_id=177, last_name="Irwin", first_name="Gwenn", grade=11),
# Storage(student_id=178, last_name="Chen", first_name="Quinton", grade=9),
# Storage(student_id=179, last_name="Snyder", first_name="Alise", grade=11),
# Storage(student_id=180, last_name="Sweet", first_name="Rob", grade=9),
# Storage(student_id=181, last_name="Owen", first_name="Ileana", grade=10),
# Storage(student_id=182, last_name="Strong", first_name="Fidela", grade=9),
# Storage(student_id=183, last_name="Pickett", first_name="Branden", grade=9),
# Storage(student_id=184, last_name="Bell", first_name="Tia", grade=12),
# Storage(student_id=185, last_name="Terry", first_name="Lilian", grade=11),
# Storage(student_id=186, last_name="Armstrong", first_name="Kasey", grade=10),
# Storage(student_id=187, last_name="Palmer", first_name="Cleopatra", grade=11),
# Storage(student_id=188, last_name="Delacruz", first_name="Yolonda", grade=12),
# Storage(student_id=189, last_name="Davidson", first_name="Irwin", grade=10),
# Storage(student_id=190, last_name="Kelley", first_name="Demetria", grade=9),
# Storage(student_id=191, last_name="Camacho", first_name="Georgiana", grade=11),
# Storage(student_id=192, last_name="Hickman", first_name="Thea", grade=12),
# Storage(student_id=193, last_name="Stafford", first_name="Louella", grade=11),
# Storage(student_id=194, last_name="Vasquez", first_name="Cody", grade=12),
# Storage(student_id=195, last_name="Dudley", first_name="Britni", grade=11),
# Storage(student_id=196, last_name="Chambers", first_name="Lesa", grade=12),
# Storage(student_id=197, last_name="Moran", first_name="Lucienne", grade=11),
# Storage(student_id=198, last_name="Sandoval", first_name="Earlene", grade=11),
# Storage(student_id=199, last_name="Simmons", first_name="Wade", grade=12),
# Storage(student_id=200, last_name="Gregory", first_name="Fran", grade=9),
# Storage(student_id=201, last_name="Pope", first_name="Pedro", grade=9),
# Storage(student_id=202, last_name="Clarke", first_name="Theola", grade=10),
# Storage(student_id=203, last_name="Allison", first_name="Henrietta", grade=10),
# Storage(student_id=204, last_name="Barnett", first_name="Dara", grade=9),
# Storage(student_id=205, last_name="Valentine", first_name="Devon", grade=11),
# Storage(student_id=206, last_name="Farmer", first_name="Audrey", grade=10),
# Storage(student_id=207, last_name="Hoover", first_name="Jesus", grade=12),
# Storage(student_id=208, last_name="Davenport", first_name="Gwendolyn", grade=9),
# Storage(student_id=209, last_name="Moses", first_name="Star", grade=9),
# Storage(student_id=210, last_name="Schwartz", first_name="Chu", grade=9),
# Storage(student_id=211, last_name="Bentley", first_name="Lavette", grade=12),
# Storage(student_id=212, last_name="Morrison", first_name="Emelda", grade=11),
# Storage(student_id=213, last_name="Albert", first_name="Bertha", grade=9),
# Storage(student_id=214, last_name="Jordan", first_name="Prince", grade=11),
# Storage(student_id=215, last_name="Thornton", first_name="Pamelia", grade=12),
# Storage(student_id=216, last_name="Cooke", first_name="Ira", grade=9),
# Storage(student_id=217, last_name="Grant", first_name="Macy", grade=9),
# Storage(student_id=218, last_name="Barrett", first_name="Alvin", grade=12),
# Storage(student_id=219, last_name="Hines", first_name="Merri", grade=11),
# Storage(student_id=220, last_name="Downs", first_name="Torrie", grade=11),
# Storage(student_id=221, last_name="Charles", first_name="Ami", grade=10),
# Storage(student_id=222, last_name="Dejesus", first_name="Tania", grade=10),
# Storage(student_id=223, last_name="Mclean", first_name="Windy", grade=10),
# Storage(student_id=224, last_name="Wilson", first_name="Kylee", grade=12),
# Storage(student_id=225, last_name="Lawrence", first_name="Candelaria", grade=11),
# Storage(student_id=226, last_name="Miles", first_name="Taisha", grade=12),
# Storage(student_id=227, last_name="Carson", first_name="Bob", grade=9),
# Storage(student_id=228, last_name="Koch", first_name="Armandina", grade=12),
# Storage(student_id=229, last_name="Kelly", first_name="Jen", grade=12),
# Storage(student_id=230, last_name="Jackson", first_name="Lashawna", grade=10),
# Storage(student_id=231, last_name="Lindsey", first_name="Jonelle", grade=11),
# Storage(student_id=232, last_name="Blake", first_name="Rosamaria", grade=12),
# Storage(student_id=233, last_name="Kirby", first_name="Helaine", grade=12),
# Storage(student_id=234, last_name="Holcomb", first_name="Sanda", grade=10),
# Storage(student_id=235, last_name="Crawford", first_name="Gabriele", grade=9),
# Storage(student_id=236, last_name="Vasquez", first_name="Amie", grade=11),
# Storage(student_id=237, last_name="Nixon", first_name="Eldon", grade=10),
# Storage(student_id=238, last_name="James", first_name="Madalyn", grade=11),
# Storage(student_id=239, last_name="Roy", first_name="Eleonore", grade=12),
# Storage(student_id=240, last_name="Jones", first_name="Alverta", grade=9),
# Storage(student_id=241, last_name="West", first_name="Blanch", grade=10),
# Storage(student_id=242, last_name="Wolfe", first_name="Kristan", grade=10),
# Storage(student_id=243, last_name="Brock", first_name="Elnora", grade=11),
# Storage(student_id=244, last_name="Snider", first_name="Grant", grade=9),
# Storage(student_id=245, last_name="Kim", first_name="Elisha", grade=11),
# Storage(student_id=246, last_name="Morton", first_name="Yasuko", grade=11),
# Storage(student_id=247, last_name="Stephens", first_name="Magdalen", grade=11),
# Storage(student_id=248, last_name="Donaldson", first_name="Jolyn", grade=9),
# Storage(student_id=249, last_name="Howell", first_name="Lola", grade=10),
# Storage(student_id=250, last_name="Aguilar", first_name="Elia", grade=10),
# Storage(student_id=251, last_name="Foreman", first_name="Tresa", grade=12),
# Storage(student_id=252, last_name="Wallace", first_name="Alyssa", grade=12),
# Storage(student_id=253, last_name="Evans", first_name="Coreen", grade=12),
# Storage(student_id=254, last_name="Gay", first_name="Clement", grade=9),
# Storage(student_id=255, last_name="Vance", first_name="Nguyet", grade=10),
# Storage(student_id=256, last_name="Woodard", first_name="Pamella", grade=10),
# Storage(student_id=257, last_name="Nieves", first_name="Katy", grade=12),
# Storage(student_id=258, last_name="Stuart", first_name="Jacklyn", grade=11),
# Storage(student_id=259, last_name="Bowman", first_name="Tomiko", grade=9),
# Storage(student_id=260, last_name="Moon", first_name="Jeniffer", grade=10),
# Storage(student_id=261, last_name="Kaufman", first_name="Natashia", grade=9),
# Storage(student_id=262, last_name="Wall", first_name="Nova", grade=9),
# Storage(student_id=263, last_name="Valencia", first_name="Bulah", grade=9),
# Storage(student_id=264, last_name="Weiss", first_name="Freeman", grade=10),
# Storage(student_id=265, last_name="Salazar", first_name="Margit", grade=11),
# Storage(student_id=266, last_name="Lamb", first_name="Retha", grade=9),
# Storage(student_id=267, last_name="Howe", first_name="Rowena", grade=9),
# Storage(student_id=268, last_name="Payne", first_name="Hubert", grade=10),
# Storage(student_id=269, last_name="Medina", first_name="Lily", grade=9),
# Storage(student_id=270, last_name="Murray", first_name="Ramonita", grade=9),
# Storage(student_id=271, last_name="Elliott", first_name="Noreen", grade=12),
# Storage(student_id=272, last_name="Hays", first_name="Amie", grade=12),
# Storage(student_id=273, last_name="Robbins", first_name="Hye", grade=11),
# Storage(student_id=274, last_name="Herring", first_name="Joana", grade=10),
# Storage(student_id=275, last_name="Suarez", first_name="Deangelo", grade=10),
# Storage(student_id=276, last_name="Mcguire", first_name="Daniele", grade=11),
# Storage(student_id=277, last_name="Valencia", first_name="Janeen", grade=12),
# Storage(student_id=278, last_name="George", first_name="Mike", grade=9),
# Storage(student_id=279, last_name="Hooper", first_name="Elva", grade=9),
# Storage(student_id=280, last_name="Small", first_name="Haydee", grade=10),
# Storage(student_id=281, last_name="Carpenter", first_name="Abby", grade=11),
# Storage(student_id=282, last_name="Cooper", first_name="Laura", grade=9),
# Storage(student_id=283, last_name="Mercer", first_name="Danyel", grade=10),
# Storage(student_id=284, last_name="Glass", first_name="Patrick", grade=12),
# Storage(student_id=285, last_name="Griffith", first_name="Rudolph", grade=11),
# Storage(student_id=286, last_name="Hutchinson", first_name="Ermelinda", grade=9),
# Storage(student_id=287, last_name="Morris", first_name="Larry", grade=10),
# Storage(student_id=288, last_name="Pena", first_name="Lynette", grade=9),
# Storage(student_id=289, last_name="Giles", first_name="Beckie", grade=11),
# Storage(student_id=290, last_name="Harrell", first_name="Eloisa", grade=12),
# Storage(student_id=291, last_name="Dunn", first_name="Larissa", grade=9),
# Storage(student_id=292, last_name="Edwards", first_name="Luigi", grade=10),
# Storage(student_id=293, last_name="Hess", first_name="Effie", grade=9),
# Storage(student_id=294, last_name="Cortez", first_name="Wilfred", grade=12),
# Storage(student_id=295, last_name="Barr", first_name="Corinne", grade=11),
# Storage(student_id=296, last_name="Hess", first_name="Susannah", grade=12),
# Storage(student_id=297, last_name="Mullen", first_name="Honey", grade=9),
# Storage(student_id=298, last_name="Reed", first_name="Julissa", grade=12),
# Storage(student_id=299, last_name="Shannon", first_name="Andree", grade=10),
# Storage(student_id=300, last_name="Chavez", first_name="Susann", grade=12),
# Storage(student_id=301, last_name="Newton", first_name="Christine", grade=11),
# Storage(student_id=302, last_name="Prince", first_name="Dina", grade=12),
# Storage(student_id=303, last_name="Washington", first_name="Autumn", grade=12),
# Storage(student_id=304, last_name="Ruiz", first_name="Eura", grade=11),
# Storage(student_id=305, last_name="Avery", first_name="Carry", grade=9),
# Storage(student_id=306, last_name="Frye", first_name="Alexa", grade=11),
# Storage(student_id=307, last_name="Ellis", first_name="Brent", grade=11),
# Storage(student_id=308, last_name="Bernard", first_name="Nicole", grade=9),
# Storage(student_id=309, last_name="Leonard", first_name="Kristan", grade=12),
# Storage(student_id=310, last_name="Estrada", first_name="Marlin", grade=9),
# Storage(student_id=311, last_name="Wilder", first_name="Kiesha", grade=12),
# Storage(student_id=312, last_name="Merritt", first_name="Kortney", grade=10),
# Storage(student_id=313, last_name="Austin", first_name="Willette", grade=12),
# Storage(student_id=314, last_name="Monroe", first_name="Tomiko", grade=10),
# Storage(student_id=315, last_name="Lewis", first_name="Rickie", grade=10),
# Storage(student_id=316, last_name="Flores", first_name="Aurora", grade=9),
# Storage(student_id=317, last_name="Olson", first_name="Angla", grade=11),
# Storage(student_id=318, last_name="Spencer", first_name="Jarred", grade=9),
# Storage(student_id=319, last_name="Sparks", first_name="Karole", grade=10),
# Storage(student_id=320, last_name="Knapp", first_name="Sophia", grade=10),
# Storage(student_id=321, last_name="Harper", first_name="Cristine", grade=10),
# Storage(student_id=322, last_name="Ortiz", first_name="Caren", grade=12),
# Storage(student_id=323, last_name="Vance", first_name="Tatiana", grade=10),
# Storage(student_id=324, last_name="Hartman", first_name="Senaida", grade=12),
# Storage(student_id=325, last_name="Barton", first_name="Bee", grade=10),
# Storage(student_id=326, last_name="Haynes", first_name="Mona", grade=10),
# Storage(student_id=327, last_name="Key", first_name="Keren", grade=10),
# Storage(student_id=328, last_name="Campbell", first_name="Shawna", grade=11),
# Storage(student_id=329, last_name="Gonzales", first_name="Katelynn", grade=12),
# Storage(student_id=330, last_name="Cook", first_name="Toney", grade=11),
# Storage(student_id=331, last_name="Blair", first_name="Marna", grade=11),
# Storage(student_id=332, last_name="Guerrero", first_name="Risa", grade=11),
# Storage(student_id=333, last_name="Hall", first_name="Lenard", grade=9),
# Storage(student_id=334, last_name="Phelps", first_name="Kiesha", grade=10),
# Storage(student_id=335, last_name="Small", first_name="Margarett", grade=9),
# Storage(student_id=336, last_name="Kirby", first_name="Jeanene", grade=9),
# Storage(student_id=337, last_name="Sullivan", first_name="Beckie", grade=12),
# Storage(student_id=338, last_name="Booth", first_name="Gaylord", grade=9),
# Storage(student_id=339, last_name="Pacheco", first_name="Simone", grade=12),
# Storage(student_id=340, last_name="Levine", first_name="Zana", grade=9),
# Storage(student_id=341, last_name="Watson", first_name="Layne", grade=10),
# Storage(student_id=342, last_name="Clements", first_name="Telma", grade=9),
# Storage(student_id=343, last_name="Emerson", first_name="Sacha", grade=10),
# Storage(student_id=344, last_name="Molina", first_name="Shirley", grade=9),
# Storage(student_id=345, last_name="Byrd", first_name="Venice", grade=12),
# Storage(student_id=346, last_name="Berg", first_name="Janell", grade=9),
# Storage(student_id=347, last_name="Mcgowan", first_name="Blossom", grade=10),
# Storage(student_id=348, last_name="Walters", first_name="Laurel", grade=12),
# Storage(student_id=349, last_name="Webster", first_name="Willy", grade=10),
# Storage(student_id=350, last_name="Hess", first_name="Basil", grade=10),
# Storage(student_id=351, last_name="Miller", first_name="Jinny", grade=9),
# Storage(student_id=352, last_name="Fulton", first_name="Juanita", grade=10),
# Storage(student_id=353, last_name="Johnston", first_name="Marcie", grade=10),
# Storage(student_id=354, last_name="Bernard", first_name="Angel", grade=9),
# Storage(student_id=355, last_name="Bonner", first_name="Kizzie", grade=11),
# Storage(student_id=356, last_name="Potter", first_name="Iva", grade=10),
# Storage(student_id=357, last_name="Head", first_name="Meaghan", grade=10),
# Storage(student_id=358, last_name="Porter", first_name="Candis", grade=12),
# Storage(student_id=359, last_name="Miranda", first_name="Sheena", grade=12),
# Storage(student_id=360, last_name="Cannon", first_name="Pasquale", grade=10),
# Storage(student_id=361, last_name="Dyer", first_name="Sheldon", grade=12),
# Storage(student_id=362, last_name="Palmer", first_name="Andy", grade=12),
# Storage(student_id=363, last_name="Keller", first_name="Kit", grade=11),
# Storage(student_id=364, last_name="Stafford", first_name="Amanda", grade=9),
# Storage(student_id=365, last_name="Hansen", first_name="Laurinda", grade=10),
# Storage(student_id=366, last_name="Zimmerman", first_name="Marth", grade=10),
# Storage(student_id=367, last_name="Booth", first_name="Jo", grade=12),
# Storage(student_id=368, last_name="Bryan", first_name="Lelah", grade=11),
# Storage(student_id=369, last_name="Kramer", first_name="Dan", grade=11),
# Storage(student_id=370, last_name="Frost", first_name="Wan", grade=9),
# Storage(student_id=371, last_name="Craig", first_name="Dion", grade=9),
# Storage(student_id=372, last_name="Waller", first_name="Nereida", grade=11),
# Storage(student_id=373, last_name="Craft", first_name="Shanta", grade=12),
# Storage(student_id=374, last_name="Pate", first_name="Loreta", grade=11),
# Storage(student_id=375, last_name="Mccray", first_name="Rhona", grade=12),
# Storage(student_id=376, last_name="Yang", first_name="My", grade=9),
# Storage(student_id=377, last_name="Pope", first_name="Victorina", grade=11),
# Storage(student_id=378, last_name="Clay", first_name="Angelique", grade=12),
# Storage(student_id=379, last_name="Garrett", first_name="Doretta", grade=10),
# Storage(student_id=380, last_name="Battle", first_name="Emily", grade=11),
# Storage(student_id=381, last_name="Sellers", first_name="Leila", grade=12),
# Storage(student_id=382, last_name="Daniels", first_name="Sergio", grade=10),
# Storage(student_id=383, last_name="Powers", first_name="Maren", grade=10),
# Storage(student_id=384, last_name="Huff", first_name="Talia", grade=12),
# Storage(student_id=385, last_name="Chen", first_name="Mildred", grade=12),
# Storage(student_id=386, last_name="Mcfarland", first_name="Golda", grade=9),
# Storage(student_id=387, last_name="Goodwin", first_name="Herschel", grade=11),
# Storage(student_id=388, last_name="Wallace", first_name="Luz", grade=12),
# Storage(student_id=389, last_name="Schwartz", first_name="Noelle", grade=11),
# Storage(student_id=390, last_name="Vaughan", first_name="Lynnette", grade=10),
# Storage(student_id=391, last_name="Castaneda", first_name="Harold", grade=10),
# Storage(student_id=392, last_name="Anderson", first_name="Kaley", grade=10),
# Storage(student_id=393, last_name="Camacho", first_name="Dorthey", grade=12),
# Storage(student_id=394, last_name="Coffey", first_name="Willian", grade=11),
# Storage(student_id=395, last_name="Wells", first_name="Lynda", grade=11),
# Storage(student_id=396, last_name="Hayden", first_name="Marybeth", grade=10),
# Storage(student_id=397, last_name="Bullock", first_name="Marty", grade=9),
# Storage(student_id=398, last_name="Jacobson", first_name="Reagan", grade=10),
# Storage(student_id=399, last_name="Reilly", first_name="Jenae", grade=10),
# Storage(student_id=400, last_name="Sharp", first_name="Claudette", grade=11),
# Storage(student_id=401, last_name="Hale", first_name="Candida", grade=12),
# Storage(student_id=402, last_name="Dennis", first_name="Darius", grade=12),
# Storage(student_id=403, last_name="Cooke", first_name="Kena", grade=12),
# Storage(student_id=404, last_name="Flowers", first_name="Drucilla", grade=10),
# Storage(student_id=405, last_name="Mcleod", first_name="Ted", grade=9),
# Storage(student_id=406, last_name="Duran", first_name="Frida", grade=11),
# Storage(student_id=407, last_name="Sullivan", first_name="Bev", grade=10),
# Storage(student_id=408, last_name="Powers", first_name="Claretta", grade=12),
# Storage(student_id=409, last_name="Rosario", first_name="Marlena", grade=12),
# Storage(student_id=410, last_name="Valentine", first_name="Hoyt", grade=10),
# Storage(student_id=411, last_name="Hammond", first_name="Dana", grade=10),
# Storage(student_id=412, last_name="Obrien", first_name="Shin", grade=10),
# Storage(student_id=413, last_name="Snider", first_name="Wesley", grade=9),
# Storage(student_id=414, last_name="Bowman", first_name="Audrie", grade=11),
# Storage(student_id=415, last_name="Vaughn", first_name="Katrina", grade=10),
# Storage(student_id=416, last_name="Singleton", first_name="Samella", grade=11),
# Storage(student_id=417, last_name="Sanchez", first_name="Brittni", grade=11),
# Storage(student_id=418, last_name="Giles", first_name="Ahmed", grade=12),
# Storage(student_id=419, last_name="Mckay", first_name="Graciela", grade=11),
# Storage(student_id=420, last_name="Bishop", first_name="Rochell", grade=12),
# Storage(student_id=421, last_name="Carr", first_name="Kaley", grade=10),
# Storage(student_id=422, last_name="Good", first_name="Marketta", grade=10),
# Storage(student_id=423, last_name="Downs", first_name="Ivy", grade=10),
# Storage(student_id=424, last_name="Frazier", first_name="Bunny", grade=12),
# Storage(student_id=425, last_name="Sykes", first_name="Columbus", grade=11),
# Storage(student_id=426, last_name="Roy", first_name="Tonisha", grade=9),
# Storage(student_id=427, last_name="Hewitt", first_name="Erica", grade=10),
# Storage(student_id=428, last_name="Wolfe", first_name="Lissette", grade=11),
# Storage(student_id=429, last_name="Dalton", first_name="Lee", grade=9),
# Storage(student_id=430, last_name="Moreno", first_name="Lakeisha", grade=9),
# Storage(student_id=431, last_name="Barlow", first_name="Ophelia", grade=9),
# Storage(student_id=432, last_name="Drake", first_name="Barry", grade=11),
# Storage(student_id=433, last_name="Stewart", first_name="Dell", grade=12),
# Storage(student_id=434, last_name="Gonzalez", first_name="Kayleen", grade=11),
# Storage(student_id=435, last_name="Skinner", first_name="Marcie", grade=9),
# Storage(student_id=436, last_name="Yang", first_name="Jonelle", grade=9),
# Storage(student_id=437, last_name="Noel", first_name="Sibyl", grade=12),
# Storage(student_id=438, last_name="Cantu", first_name="Paulette", grade=9),
# Storage(student_id=439, last_name="Gilmore", first_name="Corrinne", grade=9),
# Storage(student_id=440, last_name="Mcbride", first_name="Teri", grade=11),
# Storage(student_id=441, last_name="Paul", first_name="Rosaura", grade=11),
# Storage(student_id=442, last_name="Welch", first_name="Cammie", grade=9),
# Storage(student_id=443, last_name="Mcguire", first_name="Merilyn", grade=10),
# Storage(student_id=444, last_name="Glass", first_name="Joline", grade=10),
# Storage(student_id=445, last_name="Bryant", first_name="Shena", grade=11),
# Storage(student_id=446, last_name="Farrell", first_name="Marjory", grade=12),
# Storage(student_id=447, last_name="Mckenzie", first_name="Chara", grade=9),
# Storage(student_id=448, last_name="Camacho", first_name="Melynda", grade=11),
# Storage(student_id=449, last_name="Calhoun", first_name="Christoper", grade=10),
# Storage(student_id=450, last_name="Noble", first_name="Tangela", grade=9),
# Storage(student_id=451, last_name="Williams", first_name="Lorenza", grade=12),
# Storage(student_id=452, last_name="Thornton", first_name="Brock", grade=9),
# Storage(student_id=453, last_name="Harvey", first_name="Latonya", grade=12),
# Storage(student_id=454, last_name="Cummings", first_name="Alida", grade=12),
# Storage(student_id=455, last_name="Snow", first_name="Kayleen", grade=10),
# Storage(student_id=456, last_name="Sutton", first_name="Thersa", grade=12),
# Storage(student_id=457, last_name="Davis", first_name="Tasia", grade=10),
# Storage(student_id=458, last_name="Calhoun", first_name="Lance", grade=12),
# Storage(student_id=459, last_name="Mcmahon", first_name="Angel", grade=11),
# Storage(student_id=460, last_name="Gregory", first_name="Ardella", grade=12),
# Storage(student_id=461, last_name="Petersen", first_name="Ivy", grade=10),
# Storage(student_id=462, last_name="Crosby", first_name="Barbara", grade=12),
# Storage(student_id=463, last_name="Alexander", first_name="Carmel", grade=10),
# Storage(student_id=464, last_name="Buchanan", first_name="Shaunte", grade=12),
# Storage(student_id=465, last_name="Mathews", first_name="Marcela", grade=12),
# Storage(student_id=466, last_name="Johnson", first_name="Aleen", grade=11),
# Storage(student_id=467, last_name="Simmons", first_name="Denver", grade=11),
# Storage(student_id=468, last_name="Black", first_name="Latanya", grade=11),
# Storage(student_id=469, last_name="Barlow", first_name="Jacquelynn", grade=12),
# Storage(student_id=470, last_name="Walter", first_name="Mitzi", grade=11),
# Storage(student_id=471, last_name="Hicks", first_name="Lauralee", grade=10),
# Storage(student_id=472, last_name="Page", first_name="Cyndi", grade=11),
# Storage(student_id=473, last_name="Sheppard", first_name="Elsa", grade=9),
# Storage(student_id=474, last_name="Hinton", first_name="Alfredia", grade=10),
# Storage(student_id=475, last_name="Hopkins", first_name="Casie", grade=12),
# Storage(student_id=476, last_name="Rasmussen", first_name="Florencio", grade=11),
# Storage(student_id=477, last_name="Reyes", first_name="Su", grade=11),
# Storage(student_id=478, last_name="Harrington", first_name="Kayleen", grade=12),
# Storage(student_id=479, last_name="Morris", first_name="Ethyl", grade=12),
# Storage(student_id=480, last_name="Gilliam", first_name="Byron", grade=12),
# Storage(student_id=481, last_name="Perry", first_name="Stacy", grade=9),
# Storage(student_id=482, last_name="Hewitt", first_name="Dusty", grade=11),
# Storage(student_id=483, last_name="Shaffer", first_name="Dwain", grade=11),
# Storage(student_id=484, last_name="Bird", first_name="Delorse", grade=12),
# Storage(student_id=485, last_name="Barker", first_name="Tajuana", grade=9),
# Storage(student_id=486, last_name="Schwartz", first_name="Blair", grade=10),
# Storage(student_id=487, last_name="Rowe", first_name="Richie", grade=9),
# Storage(student_id=488, last_name="Irwin", first_name="Aline", grade=9),
# Storage(student_id=489, last_name="Cox", first_name="Christen", grade=10),
# Storage(student_id=490, last_name="Mcintyre", first_name="Beata", grade=10),
# Storage(student_id=491, last_name="William", first_name="Son", grade=9),
# Storage(student_id=492, last_name="Finch", first_name="Jc", grade=9),
# Storage(student_id=493, last_name="Simmons", first_name="Elba", grade=10),
# Storage(student_id=494, last_name="Everett", first_name="Scot", grade=12),
# Storage(student_id=495, last_name="Harmon", first_name="Clint", grade=9),
# Storage(student_id=496, last_name="Stein", first_name="Yulanda", grade=11),
# Storage(student_id=497, last_name="Baker", first_name="Jade", grade=9),
# Storage(student_id=498, last_name="Franks", first_name="Dedra", grade=11),
# Storage(student_id=499, last_name="Eaton", first_name="Ricky", grade=10),
# Storage(student_id=500, last_name="Williamson", first_name="Danyell", grade=10),
# Storage(student_id=501, last_name="Kaufman", first_name="Angeline", grade=11),
# Storage(student_id=502, last_name="Wright", first_name="Jocelyn", grade=11),
# Storage(student_id=503, last_name="Barnett", first_name="Lawanda", grade=9),
# Storage(student_id=504, last_name="Maynard", first_name="Elenor", grade=12),
# Storage(student_id=505, last_name="Morris", first_name="Haydee", grade=9),
# Storage(student_id=506, last_name="Barry", first_name="Kimberlee", grade=10),
# Storage(student_id=507, last_name="Fulton", first_name="Brent", grade=12),
# Storage(student_id=508, last_name="Rojas", first_name="Kenya", grade=11),
# Storage(student_id=509, last_name="Roth", first_name="Yuonne", grade=10),
# Storage(student_id=510, last_name="Reeves", first_name="Linh", grade=10),
# Storage(student_id=511, last_name="Mayo", first_name="Garth", grade=12),
# Storage(student_id=512, last_name="Riggs", first_name="Celestine", grade=12),
# Storage(student_id=513, last_name="Shannon", first_name="Emiko", grade=11),
# Storage(student_id=514, last_name="Doyle", first_name="Charlena", grade=9),
# Storage(student_id=515, last_name="Morgan", first_name="Mariko", grade=12),
# Storage(student_id=516, last_name="Henderson", first_name="Drew", grade=10),
# Storage(student_id=517, last_name="Woods", first_name="Antoinette", grade=11),
# Storage(student_id=518, last_name="Contreras", first_name="Yolando", grade=12),
# Storage(student_id=519, last_name="Galloway", first_name="Torri", grade=12),
# Storage(student_id=520, last_name="Church", first_name="Nelle", grade=10),
# Storage(student_id=521, last_name="Wolfe", first_name="Svetlana", grade=9),
# Storage(student_id=522, last_name="Lott", first_name="Hermina", grade=11),
# Storage(student_id=523, last_name="Mcgowan", first_name="Lynn", grade=9),
# Storage(student_id=524, last_name="Zimmerman", first_name="Drucilla", grade=12),
# Storage(student_id=525, last_name="Stanley", first_name="Waneta", grade=11),
# Storage(student_id=526, last_name="William", first_name="Brande", grade=9),
# Storage(student_id=527, last_name="Nixon", first_name="Alix", grade=11),
# Storage(student_id=528, last_name="Hayden", first_name="Bibi", grade=10),
# Storage(student_id=529, last_name="Mccullough", first_name="Alissa", grade=12),
# Storage(student_id=530, last_name="Bryant", first_name="Jona", grade=9),
# Storage(student_id=531, last_name="Jennings", first_name="Celinda", grade=12),
# Storage(student_id=532, last_name="Haley", first_name="Mozella", grade=11),
# Storage(student_id=533, last_name="Hooper", first_name="Tammera", grade=9),
# Storage(student_id=534, last_name="Leblanc", first_name="Noah", grade=11),
# Storage(student_id=535, last_name="Oneal", first_name="Yuki", grade=9),
# Storage(student_id=536, last_name="Sexton", first_name="Marvel", grade=10),
# Storage(student_id=537, last_name="May", first_name="Tashia", grade=11),
# Storage(student_id=538, last_name="Langley", first_name="Latonya", grade=10),
# Storage(student_id=539, last_name="Carr", first_name="Elenora", grade=9),
# Storage(student_id=540, last_name="Macias", first_name="Vanita", grade=10),
# Storage(student_id=541, last_name="Rojas", first_name="Christin", grade=12),
# Storage(student_id=542, last_name="Tyson", first_name="Brendon", grade=11),
# Storage(student_id=543, last_name="Reed", first_name="Catarina", grade=10),
# Storage(student_id=544, last_name="Rivas", first_name="Theda", grade=9),
# Storage(student_id=545, last_name="Vega", first_name="Verdie", grade=12),
# Storage(student_id=546, last_name="Valenzuela", first_name="Saundra", grade=9),
# Storage(student_id=547, last_name="Manning", first_name="Cordelia", grade=10),
# Storage(student_id=548, last_name="Camacho", first_name="Dollie", grade=10),
# Storage(student_id=549, last_name="Sherman", first_name="Jarrett", grade=11),
# Storage(student_id=550, last_name="Kerr", first_name="Boris", grade=9),
# Storage(student_id=551, last_name="Dillon", first_name="Jeanice", grade=9),
# Storage(student_id=552, last_name="Mooney", first_name="Kalyn", grade=9),
# Storage(student_id=553, last_name="Stuart", first_name="Theron", grade=9),
# Storage(student_id=554, last_name="Roth", first_name="Annika", grade=10),
# Storage(student_id=555, last_name="Alvarez", first_name="Jennine", grade=11),
# Storage(student_id=556, last_name="Burt", first_name="Suanne", grade=11),
# Storage(student_id=557, last_name="Watkins", first_name="Lashandra", grade=10),
# Storage(student_id=558, last_name="Watts", first_name="Janina", grade=9),
# Storage(student_id=559, last_name="Travis", first_name="Maxima", grade=9),
# Storage(student_id=560, last_name="Hebert", first_name="Joe", grade=9),
# Storage(student_id=561, last_name="Chase", first_name="Consuelo", grade=9),
# Storage(student_id=562, last_name="Sexton", first_name="Yuk", grade=10),
# Storage(student_id=563, last_name="Wong", first_name="Camellia", grade=10),
# Storage(student_id=564, last_name="Dyer", first_name="Otha", grade=9),
# Storage(student_id=565, last_name="Skinner", first_name="Isaura", grade=11),
# Storage(student_id=566, last_name="Burgess", first_name="Aleida", grade=9),
# Storage(student_id=567, last_name="Rose", first_name="Soledad", grade=11),
# Storage(student_id=568, last_name="Montoya", first_name="Imelda", grade=11),
# Storage(student_id=569, last_name="Sullivan", first_name="Verla", grade=11),
# Storage(student_id=570, last_name="Bishop", first_name="Parker", grade=12),
# Storage(student_id=571, last_name="Blake", first_name="Kandy", grade=11),
# Storage(student_id=572, last_name="Valdez", first_name="Darcel", grade=10),
# Storage(student_id=573, last_name="Hess", first_name="Deshawn", grade=11),
# Storage(student_id=574, last_name="Hooper", first_name="Rex", grade=12),
# Storage(student_id=575, last_name="Dean", first_name="Margeret", grade=12),
# Storage(student_id=576, last_name="Burke", first_name="Edmond", grade=12),
# Storage(student_id=577, last_name="Pruitt", first_name="Laure", grade=11),
# Storage(student_id=578, last_name="Tate", first_name="Millicent", grade=12),
# Storage(student_id=579, last_name="Hood", first_name="Dina", grade=9),
# Storage(student_id=580, last_name="Reyes", first_name="Meg", grade=10),
# Storage(student_id=581, last_name="Silva", first_name="Tomeka", grade=9),
# Storage(student_id=582, last_name="Fletcher", first_name="Shanell", grade=12),
# Storage(student_id=583, last_name="Cherry", first_name="Karl", grade=12),
# Storage(student_id=584, last_name="Johnson", first_name="Kristopher", grade=12),
# Storage(student_id=585, last_name="Oconnor", first_name="Sanda", grade=12),
# Storage(student_id=586, last_name="Avery", first_name="Theda", grade=12),
# Storage(student_id=587, last_name="Knox", first_name="Tashia", grade=12),
# Storage(student_id=588, last_name="Riggs", first_name="Dewayne", grade=10),
# Storage(student_id=589, last_name="Salazar", first_name="Nathanial", grade=10),
# Storage(student_id=590, last_name="Dunn", first_name="Digna", grade=10),
# Storage(student_id=591, last_name="Herman", first_name="Leonora", grade=10),
# Storage(student_id=592, last_name="Mckee", first_name="Kandis", grade=10),
# Storage(student_id=593, last_name="Schneider", first_name="Paula", grade=11),
# Storage(student_id=594, last_name="Crosby", first_name="Georgene", grade=10),
# Storage(student_id=595, last_name="Rivera", first_name="Tiara", grade=11),
# Storage(student_id=596, last_name="Kent", first_name="Abbie", grade=10),
# Storage(student_id=597, last_name="Richardson", first_name="Bong", grade=10),
# Storage(student_id=598, last_name="Blackburn", first_name="Ned", grade=10),
# Storage(student_id=599, last_name="Castillo", first_name="Sirena", grade=9),
# Storage(student_id=600, last_name="Richmond", first_name="Madalene", grade=9),
# Storage(student_id=601, last_name="Stanton", first_name="Mitchel", grade=12),
# Storage(student_id=602, last_name="Dean", first_name="Kiara", grade=9),
# Storage(student_id=603, last_name="Donaldson", first_name="Iris", grade=11),
# Storage(student_id=604, last_name="Perkins", first_name="Joshua", grade=12),
# Storage(student_id=605, last_name="Everett", first_name="Santiago", grade=10),
# Storage(student_id=606, last_name="Clarke", first_name="Ralph", grade=9),
# Storage(student_id=607, last_name="Mccullough", first_name="Alfonzo", grade=11),
# Storage(student_id=608, last_name="Raymond", first_name="Betsey", grade=9),
# Storage(student_id=609, last_name="Doyle", first_name="Yee", grade=9),
# Storage(student_id=610, last_name="Pacheco", first_name="Daniele", grade=9),
# Storage(student_id=611, last_name="Holman", first_name="Susie", grade=10),
# Storage(student_id=612, last_name="Hobbs", first_name="Arlyne", grade=11),
# Storage(student_id=613, last_name="Melton", first_name="Jeromy", grade=10),
# Storage(student_id=614, last_name="Morrow", first_name="Deshawn", grade=12),
# Storage(student_id=615, last_name="Gay", first_name="Fern", grade=9),
# Storage(student_id=616, last_name="Ellis", first_name="Jan", grade=12),
# Storage(student_id=617, last_name="Odonnell", first_name="Duncan", grade=11),
# Storage(student_id=618, last_name="Brewer", first_name="Elana", grade=11),
# Storage(student_id=619, last_name="Townsend", first_name="Christina", grade=10),
# Storage(student_id=620, last_name="Sheppard", first_name="Juli", grade=9),
# Storage(student_id=621, last_name="Alexander", first_name="Jack", grade=12),
# Storage(student_id=622, last_name="Beasley", first_name="Loan", grade=11),
# Storage(student_id=623, last_name="Matthews", first_name="Elaine", grade=9),
# Storage(student_id=624, last_name="Cohen", first_name="Darren", grade=10),
# Storage(student_id=625, last_name="Neal", first_name="Regina", grade=12),
# Storage(student_id=626, last_name="Riley", first_name="Barbra", grade=10),
# Storage(student_id=627, last_name="Montgomery", first_name="Lorrie", grade=10),
# Storage(student_id=628, last_name="Bender", first_name="Mila", grade=11),
# Storage(student_id=629, last_name="Norton", first_name="Annamaria", grade=10),
# Storage(student_id=630, last_name="Johnson", first_name="Eileen", grade=10),
# Storage(student_id=631, last_name="Hicks", first_name="Lazaro", grade=11),
# Storage(student_id=632, last_name="Lowe", first_name="Cecelia", grade=11),
# Storage(student_id=633, last_name="Rutledge", first_name="Luigi", grade=9),
# Storage(student_id=634, last_name="Perry", first_name="Chia", grade=11),
# Storage(student_id=635, last_name="Lawrence", first_name="Oren", grade=9),
# Storage(student_id=636, last_name="Bullock", first_name="Malik", grade=12),
# Storage(student_id=637, last_name="Wong", first_name="Mia", grade=12),
# Storage(student_id=638, last_name="Lowe", first_name="Laurice", grade=12),
# Storage(student_id=639, last_name="Patrick", first_name="Mireya", grade=12),
# Storage(student_id=640, last_name="Doyle", first_name="Ngoc", grade=10),
# Storage(student_id=641, last_name="Joyner", first_name="Percy", grade=10),
# Storage(student_id=642, last_name="Abbott", first_name="Cleveland", grade=12),
# Storage(student_id=643, last_name="Reynolds", first_name="Lucius", grade=12),
# Storage(student_id=644, last_name="Rodriquez", first_name="Sallie", grade=10),
# Storage(student_id=645, last_name="Reed", first_name="Ronald", grade=10),
# Storage(student_id=646, last_name="Mcintyre", first_name="Darcel", grade=11),
# Storage(student_id=647, last_name="Haynes", first_name="Shan", grade=9),
# Storage(student_id=648, last_name="Hanson", first_name="Alvin", grade=11),
# Storage(student_id=649, last_name="Gardner", first_name="Ilene", grade=11),
# Storage(student_id=650, last_name="Jacobs", first_name="Taisha", grade=9),
# Storage(student_id=651, last_name="Lynch", first_name="Aracely", grade=12),
# Storage(student_id=652, last_name="Hewitt", first_name="Flossie", grade=11),
# Storage(student_id=653, last_name="Horton", first_name="Clarence", grade=12),
# Storage(student_id=654, last_name="Holcomb", first_name="Isabel", grade=10),
# Storage(student_id=655, last_name="Merritt", first_name="Bunny", grade=10),
# Storage(student_id=656, last_name="Puckett", first_name="Faustina", grade=9),
# Storage(student_id=657, last_name="Alston", first_name="Deedra", grade=9),
# Storage(student_id=658, last_name="Franco", first_name="Aletha", grade=10),
# Storage(student_id=659, last_name="Spence", first_name="Margarite", grade=12),
# Storage(student_id=660, last_name="Lindsay", first_name="Leanne", grade=11),
# Storage(student_id=661, last_name="Nelson", first_name="Madaline", grade=11),
# Storage(student_id=662, last_name="Melton", first_name="Bud", grade=12),
# Storage(student_id=663, last_name="Hanson", first_name="Nigel", grade=10),
# Storage(student_id=664, last_name="Conner", first_name="Beatriz", grade=12),
# Storage(student_id=665, last_name="Crosby", first_name="Penney", grade=12),
# Storage(student_id=666, last_name="Woodard", first_name="Deanna", grade=10),
# Storage(student_id=667, last_name="Boyer", first_name="Jacqueline", grade=9),
# Storage(student_id=668, last_name="Macdonald", first_name="Sherley", grade=11),
# Storage(student_id=669, last_name="Webster", first_name="Tandra", grade=9),
# Storage(student_id=670, last_name="Price", first_name="Dylan", grade=10),
# Storage(student_id=671, last_name="Cantrell", first_name="Boyd", grade=9),
# Storage(student_id=672, last_name="Melendez", first_name="Jaimee", grade=9),
# Storage(student_id=673, last_name="Goff", first_name="Leticia", grade=12),
# Storage(student_id=674, last_name="Valdez", first_name="Tena", grade=9),
# Storage(student_id=675, last_name="Espinoza", first_name="Elmo", grade=11),
# Storage(student_id=676, last_name="Simmons", first_name="Jeffry", grade=9),
# Storage(student_id=677, last_name="Douglas", first_name="Lidia", grade=12),
# Storage(student_id=678, last_name="Holder", first_name="Graciela", grade=11),
# Storage(student_id=679, last_name="Bender", first_name="Nga", grade=11),
# Storage(student_id=680, last_name="Perkins", first_name="Shawanda", grade=12),
# Storage(student_id=681, last_name="Anthony", first_name="Joesph", grade=11),
# Storage(student_id=682, last_name="Maynard", first_name="Shelton", grade=10),
# Storage(student_id=683, last_name="Slater", first_name="Maricruz", grade=9),
# Storage(student_id=684, last_name="Vincent", first_name="Elana", grade=12),
# Storage(student_id=685, last_name="Jordan", first_name="Ora", grade=10),
# Storage(student_id=686, last_name="Mueller", first_name="Bethann", grade=12),
# Storage(student_id=687, last_name="Knight", first_name="Celestine", grade=11),
# Storage(student_id=688, last_name="Rowe", first_name="Patty", grade=9),
# Storage(student_id=689, last_name="Copeland", first_name="Tonette", grade=12),
# Storage(student_id=690, last_name="Leblanc", first_name="Hye", grade=11),
# Storage(student_id=691, last_name="Barry", first_name="Nova", grade=9),
# Storage(student_id=692, last_name="West", first_name="James", grade=10),
# Storage(student_id=693, last_name="Cross", first_name="Nevada", grade=10),
# Storage(student_id=694, last_name="Tran", first_name="Barrie", grade=12),
# Storage(student_id=695, last_name="Yang", first_name="Johana", grade=12),
# Storage(student_id=696, last_name="Mclean", first_name="Latricia", grade=11),
# Storage(student_id=697, last_name="Macdonald", first_name="Katharine", grade=11),
# Storage(student_id=698, last_name="Mays", first_name="Colton", grade=11),
# Storage(student_id=699, last_name="Ramirez", first_name="Sherill", grade=11),
# Storage(student_id=700, last_name="Fuller", first_name="Maryln", grade=9),
# Storage(student_id=701, last_name="Gould", first_name="Warner", grade=9),
# Storage(student_id=702, last_name="Cash", first_name="Lourie", grade=11),
# Storage(student_id=703, last_name="Dixon", first_name="Pauline", grade=12),
# Storage(student_id=704, last_name="Ewing", first_name="Glady", grade=12),
# Storage(student_id=705, last_name="Cortez", first_name="Kayleen", grade=10),
# Storage(student_id=706, last_name="Kaufman", first_name="Carlos", grade=10),
# Storage(student_id=707, last_name="Horne", first_name="Coleman", grade=11),
# Storage(student_id=708, last_name="Clayton", first_name="Raquel", grade=9),
# Storage(student_id=709, last_name="Page", first_name="Brandy", grade=9),
# Storage(student_id=710, last_name="Ray", first_name="Nova", grade=11),
# Storage(student_id=711, last_name="Summers", first_name="Elwood", grade=10),
# Storage(student_id=712, last_name="Nicholson", first_name="Avril", grade=10),
# Storage(student_id=713, last_name="Dorsey", first_name="Allen", grade=12),
# Storage(student_id=714, last_name="Greene", first_name="Natasha", grade=10),
# Storage(student_id=715, last_name="Finley", first_name="Victorina", grade=12),
# Storage(student_id=716, last_name="Hull", first_name="Alejandro", grade=9),
# Storage(student_id=717, last_name="Russo", first_name="Aleida", grade=12),
# Storage(student_id=718, last_name="Lara", first_name="Kasie", grade=9),
# Storage(student_id=719, last_name="Clements", first_name="Chaya", grade=11),
# Storage(student_id=720, last_name="Graves", first_name="Anitra", grade=11),
# Storage(student_id=721, last_name="Solis", first_name="Kaleigh", grade=12),
# Storage(student_id=722, last_name="Shaw", first_name="Brigid", grade=10),
# Storage(student_id=723, last_name="Donaldson", first_name="Shannan", grade=9),
# Storage(student_id=724, last_name="Cleveland", first_name="Kasandra", grade=9),
# Storage(student_id=725, last_name="Todd", first_name="Wynona", grade=10),
# Storage(student_id=726, last_name="Pickett", first_name="Jarrod", grade=11),
# Storage(student_id=727, last_name="Pickett", first_name="Barbie", grade=11),
# Storage(student_id=728, last_name="Barron", first_name="Corinne", grade=9),
# Storage(student_id=729, last_name="Whitley", first_name="Lindsey", grade=10),
# Storage(student_id=730, last_name="Mcdowell", first_name="Dara", grade=10),
# Storage(student_id=731, last_name="Parker", first_name="Artie", grade=12),
# Storage(student_id=732, last_name="Dickson", first_name="Riley", grade=11),
# Storage(student_id=733, last_name="Flores", first_name="Ann", grade=10),
# Storage(student_id=734, last_name="Dejesus", first_name="Darcy", grade=12),
# Storage(student_id=735, last_name="Higgins", first_name="Corrinne", grade=9),
# Storage(student_id=736, last_name="Buckley", first_name="Truman", grade=10),
# Storage(student_id=737, last_name="Slater", first_name="Sherice", grade=9),
# Storage(student_id=738, last_name="Fletcher", first_name="Letisha", grade=9),
# Storage(student_id=739, last_name="Shelton", first_name="Carrol", grade=10),
# Storage(student_id=740, last_name="Garrett", first_name="Joesph", grade=11),
# Storage(student_id=741, last_name="Moreno", first_name="Kelly", grade=12),
# Storage(student_id=742, last_name="Franco", first_name="Nikia", grade=9),
# Storage(student_id=743, last_name="Hodges", first_name="Heidy", grade=11),
# Storage(student_id=744, last_name="Johnson", first_name="Sirena", grade=10),
# Storage(student_id=745, last_name="Weaver", first_name="Aletha", grade=10),
# Storage(student_id=746, last_name="Johnston", first_name="Skye", grade=11),
# Storage(student_id=747, last_name="Swanson", first_name="Venetta", grade=9),
# Storage(student_id=748, last_name="Hendricks", first_name="Yi", grade=12),
# Storage(student_id=749, last_name="Tyler", first_name="Eloise", grade=11),
# Storage(student_id=750, last_name="Norton", first_name="Christoper", grade=10),
# Storage(student_id=751, last_name="Wilder", first_name="Ehtel", grade=10),
# Storage(student_id=752, last_name="Harris", first_name="Donnette", grade=11),
# Storage(student_id=753, last_name="Wilkerson", first_name="Shanon", grade=12),
# Storage(student_id=754, last_name="Harding", first_name="Oliva", grade=10),
# Storage(student_id=755, last_name="Cote", first_name="Lottie", grade=12),
# Storage(student_id=756, last_name="Owen", first_name="Eura", grade=12),
# Storage(student_id=757, last_name="Berg", first_name="Delsie", grade=12),
# Storage(student_id=758, last_name="Snyder", first_name="Jim", grade=12),
# Storage(student_id=759, last_name="Gibbs", first_name="Imelda", grade=10),
# Storage(student_id=760, last_name="Irwin", first_name="Desiree", grade=10),
# Storage(student_id=761, last_name="Davenport", first_name="Rosia", grade=9),
# Storage(student_id=762, last_name="Melton", first_name="Palmira", grade=11),
# Storage(student_id=763, last_name="Davenport", first_name="Joesph", grade=11),
# Storage(student_id=764, last_name="Perez", first_name="Charlene", grade=9),
# Storage(student_id=765, last_name="Preston", first_name="Sabrina", grade=10),
# Storage(student_id=766, last_name="Gibbs", first_name="Kirstie", grade=9),
# Storage(student_id=767, last_name="Valenzuela", first_name="Chrissy", grade=11),
# Storage(student_id=768, last_name="Gregory", first_name="Chanelle", grade=11),
# Storage(student_id=769, last_name="Glenn", first_name="Doloris", grade=12),
# Storage(student_id=770, last_name="Rojas", first_name="Cedric", grade=12),
# Storage(student_id=771, last_name="Le", first_name="Fredrick", grade=10),
# Storage(student_id=772, last_name="Meyers", first_name="Nga", grade=12),
# Storage(student_id=773, last_name="Anthony", first_name="Mauricio", grade=9),
# Storage(student_id=774, last_name="Salas", first_name="Cortney", grade=12),
# Storage(student_id=775, last_name="Barnes", first_name="Bailey", grade=11),
# Storage(student_id=776, last_name="Forbes", first_name="Kathaleen", grade=10),
# Storage(student_id=777, last_name="Cooper", first_name="Classie", grade=12),
# Storage(student_id=778, last_name="Hewitt", first_name="Demarcus", grade=11),
# Storage(student_id=779, last_name="Estes", first_name="Ja", grade=12),
# Storage(student_id=780, last_name="Mullen", first_name="Charise", grade=10),
# Storage(student_id=781, last_name="Mendoza", first_name="Shyla", grade=12),
# Storage(student_id=782, last_name="Mullen", first_name="Jestine", grade=9),
# Storage(student_id=783, last_name="Mcmahon", first_name="Celena", grade=11),
# Storage(student_id=784, last_name="Gallagher", first_name="Aisha", grade=12),
# Storage(student_id=785, last_name="Witt", first_name="Herma", grade=12),
# Storage(student_id=786, last_name="Hunt", first_name="Vivan", grade=12),
# Storage(student_id=787, last_name="Ball", first_name="Herma", grade=10),
# Storage(student_id=788, last_name="Diaz", first_name="Felicia", grade=11),
# Storage(student_id=789, last_name="Lott", first_name="Jena", grade=12),
# Storage(student_id=790, last_name="Curtis", first_name="Carrie", grade=12),
# Storage(student_id=791, last_name="Pena", first_name="Kenyatta", grade=10),
# Storage(student_id=792, last_name="Knowles", first_name="Rory", grade=9),
# Storage(student_id=793, last_name="England", first_name="Lavera", grade=10),
# Storage(student_id=794, last_name="Mcdowell", first_name="Leoma", grade=9),
# Storage(student_id=795, last_name="Santos", first_name="Jaymie", grade=10),
# Storage(student_id=796, last_name="Estes", first_name="Lisa", grade=11),
# Storage(student_id=797, last_name="Black", first_name="Noriko", grade=12),
# Storage(student_id=798, last_name="Dyer", first_name="Jaimie", grade=10),
# Storage(student_id=799, last_name="Heath", first_name="Myung", grade=10),
# Storage(student_id=800, last_name="Thornton", first_name="Dorris", grade=12),
# Storage(student_id=801, last_name="Manning", first_name="Neda", grade=9),
# Storage(student_id=802, last_name="Carroll", first_name="Dorthey", grade=10),
# Storage(student_id=803, last_name="Scott", first_name="Jonathan", grade=11),
# Storage(student_id=804, last_name="Hays", first_name="Laurel", grade=11),
# Storage(student_id=805, last_name="Santana", first_name="Eloisa", grade=11),
# Storage(student_id=806, last_name="Nunez", first_name="Serena", grade=10),
# Storage(student_id=807, last_name="Beasley", first_name="Ione", grade=10),
# Storage(student_id=808, last_name="Hall", first_name="Carrie", grade=9),
# Storage(student_id=809, last_name="Barker", first_name="Cherrie", grade=10),
# Storage(student_id=810, last_name="Ochoa", first_name="Wilfred", grade=10),
# Storage(student_id=811, last_name="Clements", first_name="Palmer", grade=11),
# Storage(student_id=812, last_name="Hall", first_name="Don", grade=11),
# Storage(student_id=813, last_name="Prince", first_name="Nila", grade=11),
# Storage(student_id=814, last_name="Wheeler", first_name="Coral", grade=11),
# Storage(student_id=815, last_name="Camacho", first_name="Ludie", grade=10),
# Storage(student_id=816, last_name="Byrd", first_name="Rafaela", grade=10),
# Storage(student_id=817, last_name="Delacruz", first_name="Cristine", grade=11),
# Storage(student_id=818, last_name="Kelley", first_name="Theron", grade=10),
# Storage(student_id=819, last_name="Gentry", first_name="Tawanda", grade=9),
# Storage(student_id=820, last_name="Mathews", first_name="Kory", grade=12),
# Storage(student_id=821, last_name="Solomon", first_name="Noelle", grade=11),
# Storage(student_id=822, last_name="Wolfe", first_name="Darby", grade=12),
# Storage(student_id=823, last_name="Parrish", first_name="Sade", grade=11),
# Storage(student_id=824, last_name="Bates", first_name="Modesta", grade=9),
# Storage(student_id=825, last_name="Wilkinson", first_name="Charlesetta", grade=12),
# Storage(student_id=826, last_name="Doyle", first_name="Karyn", grade=11),
# Storage(student_id=827, last_name="Rivas", first_name="Malisa", grade=12),
# Storage(student_id=828, last_name="Romero", first_name="Blanch", grade=10),
# Storage(student_id=829, last_name="Lewis", first_name="Joaquin", grade=12),
# Storage(student_id=830, last_name="Rivas", first_name="Diedra", grade=9),
# Storage(student_id=831, last_name="Monroe", first_name="Alexa", grade=12),
# Storage(student_id=832, last_name="Banks", first_name="Edie", grade=11),
# Storage(student_id=833, last_name="Cooper", first_name="Yasmin", grade=12),
# Storage(student_id=834, last_name="Frederick", first_name="Jessi", grade=10),
# Storage(student_id=835, last_name="Chandler", first_name="Alishia", grade=9),
# Storage(student_id=836, last_name="Meyer", first_name="Cuc", grade=12),
# Storage(student_id=837, last_name="Riggs", first_name="Jerrica", grade=11),
# Storage(student_id=838, last_name="Morton", first_name="Rachal", grade=11),
# Storage(student_id=839, last_name="Puckett", first_name="Jayne", grade=9),
# Storage(student_id=840, last_name="Taylor", first_name="Basilia", grade=11),
# Storage(student_id=841, last_name="Mathis", first_name="Rae", grade=11),
# Storage(student_id=842, last_name="Gilbert", first_name="Nichelle", grade=12),
# Storage(student_id=843, last_name="Ware", first_name="Hai", grade=10),
# Storage(student_id=844, last_name="Salinas", first_name="Meredith", grade=9),
# Storage(student_id=845, last_name="Newton", first_name="Darcy", grade=9),
# Storage(student_id=846, last_name="Fields", first_name="Deandrea", grade=11),
# Storage(student_id=847, last_name="Navarro", first_name="Sondra", grade=9),
# Storage(student_id=848, last_name="Pratt", first_name="Arlette", grade=11),
# Storage(student_id=849, last_name="Lang", first_name="Hyacinth", grade=9),
# Storage(student_id=850, last_name="Cobb", first_name="Erline", grade=12),
# Storage(student_id=851, last_name="Kane", first_name="Susie", grade=9),
# Storage(student_id=852, last_name="Atkinson", first_name="Lakeisha", grade=9),
# Storage(student_id=853, last_name="Drake", first_name="Iva", grade=12),
# Storage(student_id=854, last_name="Parker", first_name="Janay", grade=10),
# Storage(student_id=855, last_name="Callahan", first_name="Alissa", grade=12),
# Storage(student_id=856, last_name="Dunn", first_name="Mckenzie", grade=10),
# Storage(student_id=857, last_name="Herring", first_name="Enid", grade=9),
# Storage(student_id=858, last_name="Wolfe", first_name="Esta", grade=11),
# Storage(student_id=859, last_name="Salas", first_name="Vivienne", grade=11),
# Storage(student_id=860, last_name="Daugherty", first_name="Otilia", grade=12),
# Storage(student_id=861, last_name="Lowe", first_name="Elana", grade=12),
# Storage(student_id=862, last_name="Lopez", first_name="Veola", grade=11),
# Storage(student_id=863, last_name="Mcfarland", first_name="Genoveva", grade=11),
# Storage(student_id=864, last_name="Williamson", first_name="Candida", grade=12),
# Storage(student_id=865, last_name="Zamora", first_name="Mira", grade=11),
# Storage(student_id=866, last_name="Cabrera", first_name="Jacqui", grade=10),
# Storage(student_id=867, last_name="Wallace", first_name="Curtis", grade=10),
# Storage(student_id=868, last_name="Espinoza", first_name="Terrence", grade=11),
# Storage(student_id=869, last_name="Fletcher", first_name="Phylis", grade=11),
# Storage(student_id=870, last_name="Lynch", first_name="Laquanda", grade=11),
# Storage(student_id=871, last_name="Carson", first_name="Shanae", grade=9),
# Storage(student_id=872, last_name="Hopkins", first_name="Colette", grade=9),
# Storage(student_id=873, last_name="Rhodes", first_name="Isa", grade=9),
# Storage(student_id=874, last_name="Mitchell", first_name="Luz", grade=9),
# Storage(student_id=875, last_name="Ferrell", first_name="Lael", grade=12),
# Storage(student_id=876, last_name="Curry", first_name="Sid", grade=11),
# Storage(student_id=877, last_name="Meyer", first_name="Mickey", grade=10),
# Storage(student_id=878, last_name="Chapman", first_name="Shalanda", grade=10),
# Storage(student_id=879, last_name="Ryan", first_name="Carter", grade=11),
# Storage(student_id=880, last_name="Carrillo", first_name="Ginette", grade=11),
# Storage(student_id=881, last_name="Hatfield", first_name="Shelba", grade=11),
# Storage(student_id=882, last_name="Reynolds", first_name="Floria", grade=9),
# Storage(student_id=883, last_name="Johns", first_name="Tawana", grade=12),
# Storage(student_id=884, last_name="Turner", first_name="Cyril", grade=9),
# Storage(student_id=885, last_name="Stewart", first_name="Shanelle", grade=11),
# Storage(student_id=886, last_name="Meadows", first_name="Emerita", grade=12),
# Storage(student_id=887, last_name="Pitts", first_name="Kaley", grade=9),
# Storage(student_id=888, last_name="Castillo", first_name="Suzi", grade=12),
# Storage(student_id=889, last_name="Levine", first_name="Arletta", grade=12),
# Storage(student_id=890, last_name="Mccullough", first_name="Rodolfo", grade=10),
# Storage(student_id=891, last_name="Franks", first_name="Hazel", grade=10),
# Storage(student_id=892, last_name="Stephenson", first_name="Enedina", grade=11),
# Storage(student_id=893, last_name="Padilla", first_name="Magda", grade=9),
# Storage(student_id=894, last_name="Wiley", first_name="Vannessa", grade=10),
# Storage(student_id=895, last_name="Cook", first_name="Fatimah", grade=9),
# Storage(student_id=896, last_name="Thompson", first_name="Bettyann", grade=12),
# Storage(student_id=897, last_name="Knapp", first_name="Miriam", grade=12),
# Storage(student_id=898, last_name="Guy", first_name="Mirian", grade=9),
# Storage(student_id=899, last_name="Le", first_name="Sharika", grade=12),
# Storage(student_id=900, last_name="Kelly", first_name="Ken", grade=9),
# Storage(student_id=901, last_name="Ayala", first_name="Ayanna", grade=12),
# Storage(student_id=902, last_name="Singleton", first_name="Zita", grade=12),
# Storage(student_id=903, last_name="Coleman", first_name="Marquitta", grade=10),
# Storage(student_id=904, last_name="Coffey", first_name="Coral", grade=9),
# Storage(student_id=905, last_name="Jordan", first_name="Anne", grade=10),
# Storage(student_id=906, last_name="Alston", first_name="Kyle", grade=11),
# Storage(student_id=907, last_name="Kent", first_name="Lamonica", grade=9),
# Storage(student_id=908, last_name="Bernard", first_name="Edward", grade=10),
# Storage(student_id=909, last_name="Vincent", first_name="Filiberto", grade=10),
# Storage(student_id=910, last_name="Boyle", first_name="Tatiana", grade=11),
# Storage(student_id=911, last_name="Park", first_name="Olevia", grade=11),
# Storage(student_id=912, last_name="Long", first_name="Maribel", grade=9),
# Storage(student_id=913, last_name="Hughes", first_name="Jeni", grade=10),
# Storage(student_id=914, last_name="Knight", first_name="Paul", grade=11),
# Storage(student_id=915, last_name="Hess", first_name="Magaret", grade=12),
# Storage(student_id=916, last_name="Graham", first_name="Jolynn", grade=12),
# Storage(student_id=917, last_name="Ray", first_name="Tari", grade=12),
# Storage(student_id=918, last_name="Bryant", first_name="Brynn", grade=9),
# Storage(student_id=919, last_name="Atkins", first_name="Denese", grade=11),
# Storage(student_id=920, last_name="Holcomb", first_name="Whitney", grade=12),
# Storage(student_id=921, last_name="Cline", first_name="Ahmed", grade=12),
# Storage(student_id=922, last_name="Velasquez", first_name="Kelsie", grade=9),
# Storage(student_id=923, last_name="Castro", first_name="Marylyn", grade=10),
# Storage(student_id=924, last_name="Salazar", first_name="Yesenia", grade=10),
# Storage(student_id=925, last_name="Rowe", first_name="Maurita", grade=9),
# Storage(student_id=926, last_name="Giles", first_name="Marita", grade=12),
# Storage(student_id=927, last_name="Stone", first_name="Bridgett", grade=11),
# Storage(student_id=928, last_name="Crane", first_name="Janita", grade=9),
# Storage(student_id=929, last_name="Stein", first_name="Lamar", grade=9),
# Storage(student_id=930, last_name="Weaver", first_name="Salome", grade=11),
# Storage(student_id=931, last_name="Garrett", first_name="Twila", grade=11),
# Storage(student_id=932, last_name="Herring", first_name="Milton", grade=11),
# Storage(student_id=933, last_name="Castillo", first_name="Shalanda", grade=12),
# Storage(student_id=934, last_name="Rodriguez", first_name="Annabelle", grade=11),
# Storage(student_id=935, last_name="Dickerson", first_name="Antonette", grade=11),
# Storage(student_id=936, last_name="Anderson", first_name="Krissy", grade=9),
# Storage(student_id=937, last_name="Rios", first_name="Marcene", grade=10),
# Storage(student_id=938, last_name="Perkins", first_name="Luella", grade=10),
# Storage(student_id=939, last_name="Church", first_name="Phillip", grade=10),
# Storage(student_id=940, last_name="Suarez", first_name="Jessika", grade=10),
# Storage(student_id=941, last_name="Francis", first_name="Della", grade=10),
# Storage(student_id=942, last_name="Gonzalez", first_name="Lawana", grade=10),
# Storage(student_id=943, last_name="Mcguire", first_name="Rocky", grade=12),
# Storage(student_id=944, last_name="Hudson", first_name="Marlyn", grade=10),
# Storage(student_id=945, last_name="Zamora", first_name="Marco", grade=9),
# Storage(student_id=946, last_name="Hardy", first_name="Sunday", grade=9),
# Storage(student_id=947, last_name="Bray", first_name="Delfina", grade=10),
# Storage(student_id=948, last_name="Newman", first_name="Nida", grade=12),
# Storage(student_id=949, last_name="Ratliff", first_name="Gricelda", grade=9),
# Storage(student_id=950, last_name="Garner", first_name="Luisa", grade=12),
# Storage(student_id=951, last_name="Fleming", first_name="Charlette", grade=11),
# Storage(student_id=952, last_name="Oliver", first_name="Susanna", grade=11),
# Storage(student_id=953, last_name="Bond", first_name="Neoma", grade=10),
# Storage(student_id=954, last_name="Patrick", first_name="Brandon", grade=9),
# Storage(student_id=955, last_name="Kinney", first_name="Lisandra", grade=12),
# Storage(student_id=956, last_name="Hill", first_name="Milda", grade=9),
# Storage(student_id=957, last_name="Parsons", first_name="Wanetta", grade=11),
# Storage(student_id=958, last_name="Rogers", first_name="Colin", grade=12),
# Storage(student_id=959, last_name="Castaneda", first_name="Elinor", grade=10),
# Storage(student_id=960, last_name="Trevino", first_name="Darell", grade=11),
# Storage(student_id=961, last_name="Rowland", first_name="Jeni", grade=12),
# Storage(student_id=962, last_name="Mckay", first_name="Yen", grade=10),
# Storage(student_id=963, last_name="Sullivan", first_name="Lilliam", grade=12),
# Storage(student_id=964, last_name="Riggs", first_name="Marquita", grade=11),
# Storage(student_id=965, last_name="Hensley", first_name="Coralee", grade=10),
# Storage(student_id=966, last_name="Holcomb", first_name="Viki", grade=9),
# Storage(student_id=967, last_name="Fowler", first_name="Vina", grade=11),
# Storage(student_id=968, last_name="Battle", first_name="Man", grade=11),
# Storage(student_id=969, last_name="Whitley", first_name="Lakendra", grade=10),
# Storage(student_id=970, last_name="Roy", first_name="Landon", grade=12),
# Storage(student_id=971, last_name="Key", first_name="Zana", grade=9),
# Storage(student_id=972, last_name="Klein", first_name="Kimberlie", grade=11),
# Storage(student_id=973, last_name="Lowery", first_name="Marge", grade=12),
# Storage(student_id=974, last_name="Bruce", first_name="Larhonda", grade=9),
# Storage(student_id=975, last_name="Stephens", first_name="Hortensia", grade=10),
# Storage(student_id=976, last_name="Pacheco", first_name="Paulina", grade=10),
# Storage(student_id=977, last_name="Hood", first_name="Joelle", grade=11),
# Storage(student_id=978, last_name="Hunt", first_name="Stanford", grade=10),
# Storage(student_id=979, last_name="Mcneil", first_name="Carolin", grade=10),
# Storage(student_id=980, last_name="Tanner", first_name="Dayle", grade=12),
# Storage(student_id=981, last_name="French", first_name="Tisha", grade=12),
# Storage(student_id=982, last_name="Holland", first_name="Maryland", grade=11),
# Storage(student_id=983, last_name="Jackson", first_name="Azalee", grade=11),
# Storage(student_id=984, last_name="Camacho", first_name="Marcel", grade=10),
# Storage(student_id=985, last_name="Cervantes", first_name="Stephane", grade=12),
# Storage(student_id=986, last_name="Boyle", first_name="Jewel", grade=10),
# Storage(student_id=987, last_name="Humphrey", first_name="Akiko", grade=12),
# Storage(student_id=988, last_name="Medina", first_name="Herbert", grade=11),
# Storage(student_id=989, last_name="Stark", first_name="Rosaria", grade=10),
# Storage(student_id=990, last_name="Hernandez", first_name="Lila", grade=10),
# Storage(student_id=991, last_name="Carney", first_name="Antone", grade=10),
# Storage(student_id=992, last_name="Mcclain", first_name="Beckie", grade=9),
# Storage(student_id=993, last_name="Booker", first_name="Kacy", grade=11),
# Storage(student_id=994, last_name="Durham", first_name="Buffy", grade=9),
# Storage(student_id=995, last_name="Warner", first_name="Johnna", grade=9),
# Storage(student_id=996, last_name="Barlow", first_name="Diane", grade=9),
# Storage(student_id=997, last_name="Thomas", first_name="Dewitt", grade=11),
# Storage(student_id=998, last_name="Wise", first_name="Stephani", grade=12),
# Storage(student_id=999, last_name="Solis", first_name="Keira", grade=10),
# Storage(student_id=1000, last_name="Battle", first_name="Harris", grade=9)
# ]

# for p in people:
# 	db.person.update_or_insert(db.person.student_id==p.student_id, grade=p.grade)


## after defining tables, uncomment below to enable auditing
# auth.enable_record_versioning(db)
